"""Init

Revision ID: 2caf8551730f
Revises: 2ee94ed12eb0
Create Date: 2023-01-13 19:57:43.436797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2caf8551730f'
down_revision = '2ee94ed12eb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
