"""Init

Revision ID: 2ee94ed12eb0
Revises: 360f8ef791c9
Create Date: 2023-01-13 19:50:13.030048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee94ed12eb0'
down_revision = '360f8ef791c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
