"""Init

Revision ID: 360f8ef791c9
Revises: 903b3debfa01
Create Date: 2023-01-13 19:44:13.777327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360f8ef791c9'
down_revision = '903b3debfa01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
