"""Init

Revision ID: 5b549cc43693
Revises: 2caf8551730f
Create Date: 2023-01-13 19:58:37.086461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b549cc43693'
down_revision = '2caf8551730f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
